### ISSUE TITLE
light and dark theme

### ISSUE THREAD

**Issue by SHARMA-1729** [bsoc-bitbyte/resource-sharing#11]
I am improving light and dark theme.

**Comment by sambhavgupta0705** [comment]
Hey @SHARMA-1729 ,you may work on this issue.
Just remember to use tailwind for switching themes and don't hesitate to ask any doubt.
Notion link for reference : https://grey-soybean-258.notion.site/Resource-Sharing-da954660ddf44771895d56321195aae4

**Comment by sambhavgupta0705** [comment]
@SHARMA-1729 any updates????

**Comment by abansal15** [comment]
Hello @sambhavgupta0705  I can try to this issue can you pls assign it to me

**Comment by Anurag607** [comment]
@abansal15 We can assign it to you but kindly give us a brief about how you will be approaching this issue before that

**Comment by NightFury742** [comment]
@Anurag607 @sambhavgupta0705 Can I work on this issue? I will be using useState hook and  onChange event listener which will change the state's value which in turn will render different colours depending upon the theme.

**Comment by sambhavgupta0705** [comment]
For now I am keeping this issue on hold as first we should build our website basic structure in light mode then we will shift to dark mode
