### ISSUE TITLE
Create a Login page and a Sign up page

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#12]
- [ ] Login Page
- [ ] Sign Page
- [ ] Reset Password

Login page needs two components-
1. One for native login (email + password + remember me checkbox + reset password)
2. Second for google sign in

Signup page also needs two components-
1. One for native login (username + email + password + confirm password)
2. Second for google sign in

Reset Password page simply needs an email input field and submit button.

On checking "remember me" the users credentials should be stored in the local storage for a duration 1 week.
No need to create Submit Handlers for the forms right now

Both the pages need to be responsive and in accordance with ongoing color scheme and typography.
Take care to maintain consistency in both aspects as well as padding and margin.

For reference: 
- https://dribbble.com/shots/17408454-Login-Form-Prototype
- https://dribbble.com/shots/16316303-Login-and-Sign-up-Screens

Figma link - https://www.figma.com/file/BFLdR6rSd6rqjsx3nYepUT/UniShare?type=design&node-id=0%3A1&t=C0pM1FpOhI2hNqn7-1

**Comment by shramanpaul** [comment]
sir i want to work on this issue

**Comment by satcode8** [comment]
sir im interested in working on this issue.

**Comment by Anurag607** [comment]
@satcode8 I am afraid @shramanpaul asked to be assign first, I will open a new issue you can work on that if you want.

**Comment by shramanpaul** [comment]
ok sir

**Comment by satcode8** [comment]
> @satcode8 I am afraid @shramanpaul asked to be assign first, I will open a new issue you can work on that if you want.

sure sir,

**Comment by shramanpaul** [comment]
@Anurag607  in which folder should I create the above files for the required

**Comment by Anurag607** [comment]
Login Page - pages/login/index.jsx , same for signup and reset pages.
Also remember to add routes for these pages

**Comment by shramanpaul** [comment]
@Anurag607  sir can I upload the project in parts as I have done most of the sign up and login frontend work I have to further add 
1. remember me
2.localstorage
3.google authentication

**Comment by Anurag607** [comment]
Yes sure, but make sure to name your branch after the page you are submitting so that it is easier to distinguish between tasks.
Also set up the route for the page you submitting.
You don't need to add any functionalities to the Google authentication button yet...just keep a simple button for future use.

**Comment by shramanpaul** [comment]
Ok @Anurag607

**Comment by Anurag607** [comment]
@shramanpaul any updates?

**Comment by shramanpaul** [comment]
@Anurag607 I have made a PR, please review it.
