### ISSUE TITLE
Create a page for listing materials

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#13]
We need a page for viewing all the materials corresponding to any of the categories.
The user upon interacting with any of the category cards in the main landing page will be redirected to this page.

1. First is the navbar.
2. Second, this page needs an introductory component with the name of the category and how many materials are available under this category.
3. Third we need a search bar, no need to add submit button.
4. Fourth we need a component for sorting and filtering i.e. a sort bar, no need to add any functionalities just yet. This component, needs buttons for sorting by type, date, branch, year.
5. Fifth we need a component to view all the materials in the form of cards, the card needs to have a title, date of upload, a preview button and a download button as well as a bookmark button/icon.
6. Sixth is the footer component same as the one used in the landing page.

For reference - https://meganmartin.net/wp-content/uploads/2019/10/The-2-Types-of-Resources-Pages-and-Which-One-is-Right-for-Your-Website-6.jpg

Figma Link - https://www.figma.com/file/BFLdR6rSd6rqjsx3nYepUT/UniShare?type=design&node-id=0-1&t=Aubr0bmQO9JWssuZ-0

**Comment by anshikkay** [comment]
hello sir,i want to work on this issue.
please assign it to me.
thank you

**Comment by Anurag607** [comment]
okay, I will assign it to you.

**Comment by Anurag607** [comment]
Try to make it responsive as well.

**Comment by anshikkay** [comment]
@Anurag607
Do I need to add JavaScript and make every element responsive?

**Comment by anshikkay** [comment]
@Anurag607 
Still working on it.

**Comment by Anurag607** [comment]
yes, you have to make it responsive, however no need to add any functionalities yet. Also before proceeding make sure you pull from the master branch

**Comment by Anurag607** [comment]
Do share any screen shots of the page here

**Comment by anshikkay** [comment]
hello @Anurag607 
here is the idea of the page, i am working on.
Do share your feedback,so i will continue.
![Screenshot (123)](https://github.com/bsoc-bitbyte/resource-sharing/assets/129502224/b8f9e052-dd15-42b5-bc8f-2300abb97bbb)
thank you.

**Comment by Anurag607** [comment]
the cards will be something like this:
<img width="270" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/e8e6a475-25e1-4cc9-9245-ddd644fa6cc3">

**Comment by Anurag607** [comment]
the image, the name of material and it's brief description.
below it two buttons download and preview

**Comment by Anurag607** [comment]
i have updated the design for the pages please go through it..

**Comment by Akashsah2003** [comment]
If no one is working on this issue, I would like to work on it. Please assign this issue to me.

**Comment by sambhavgupta0705** [comment]
yes @Akashsah2003 you can take this up.
But first discuss about your approach

**Comment by Akashsah2003** [comment]
> yes @Akashsah2003 you can take this up. But first discuss about your approach

> Sure first I will create a route which will take category of materials as params. 
> After that I will create a state variable that will be an object which will be a result of a fetch request. For now I will be using some fake products API for the request. 
> Then after that I will create a banner having category name and number of items as list size in the object state variable. After that I will make the search and filter bar.
> Lastly I will render the products using the state variable.

**Comment by Akashsah2003** [comment]
> > yes @Akashsah2003 you can take this up. But first discuss about your approach
> 
> * Sure first I will create a route which will take category of materials as params.
> * After that I will create a state variable that will be an object which will be a result of a fetch request. For now I will be using some fake products API for the request.
> * Then after that I will create a banner having category name and number of items as list size in the object state variable. After that I will make the search and filter bar.
> * Lastly I will render the products using the state variable.

@sambhavgupta0705 Please give your suggestions and reviews on it.

**Comment by Anurag607** [comment]
Your approach seems fine to me. But maybe we can also think about locally caching the fetched data 🤔?

**Comment by Akashsah2003** [comment]
I am working on it will open a pull request today.
