### ISSUE TITLE
Implement a Nav Bar for the site

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#2]
The design for the navbar is given in the Figma design which can be accessed via the notion link provided in the readme.
The design is subject to change, if you have any better idea feel free to share and implement.

**Comment by Akashsah2003** [comment]
Sir I would like to work on this issue. Please assign me this issue.

**Comment by Anurag607** [comment]
okay.

**Comment by Anurag607** [comment]
@Akashsah2003  Any progress so far?

**Comment by Akashsah2003** [comment]
> @Akashsah2003 Any progress so far?

Sir I am trying to use tailwind CSS but I am having problem in using tailwind CSS. I am using tailwind CSS classes but the CSS is not applied I need some help regarding that. Like in the navbar component I am using text-red etc but it is not applying.

**Comment by Anurag607** [comment]
try text-red-500
refer to this for color: https://tailwindcss.com/docs/customizing-colors
also if you face any such problems just ping me here or go over the docs (they are really good)

**Comment by Akashsah2003** [comment]
![prh1](https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/fdca253f-fab4-4c03-b1cc-6153a6fe6b2f)
![prh2](https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/01289452-f972-46c3-8636-578ac0a6ed58)
I am using the correct classes I think but the CSS is not applied. I worked with tailwind CSS on a repo before there I just used the className and it worked but here it's not working.
Please review and help.

**Comment by Anurag607** [comment]
i have made some changes
pull from the master branch and then try

**Comment by Akashsah2003** [comment]
> i have made some changes pull from the master branch and then try

Yes now it's working I will soon resolve this issue. Thank you.

**Comment by Anurag607** [comment]
@Akashsah2003 any updates?
