### ISSUE TITLE
[Feature Request]: place all the images in the src/assets folder 

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#24]
### Is your feature request related to a problem? Please describe.

Public folder is only used for favicon and global images .So shift all images from public to src/assets folder

### Describe the solution you'd like

...

**Comment by NightFury742** [comment]
I want to work on this issue @sambhavgupta0705 ,can you please assign it to me.

**Comment by sambhavgupta0705** [comment]
yes @NightFury742 you can work on this one.

**Comment by sambhavgupta0705** [comment]
just let the vite.svg icon be in [public](https://github.com/bsoc-bitbyte/resource-sharing/tree/master/public) folder and all other images must be shifted to src folder and make the changes in code accordingly.
