### ISSUE TITLE
[Feature Request]: SignUp Page

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#26]
### Is your feature request related to a problem? Please describe.

..

### Describe the solution you'd like

..

**Comment by NightFury742** [comment]
@sambhavgupta0705  I would like to work on this issue please assign it to me.
I will be using a theme which matches the login page.

**Comment by sambhavgupta0705** [comment]
@NightFury742 this issue was discussed previously with @shramanpaul in a previous issue.
So he will be working on it.

**Comment by NightFury742** [comment]
Ok @sambhavgupta0705, no problem.
