### ISSUE TITLE
[Feature Request]: place content.jsx file in components folder

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#27]
### Is your feature request related to a problem? Please describe.

..

### Describe the solution you'd like

currently the content.jsx file is placed in pages folder which should be shifted to components folder and other necessary changes should also be made

**Comment by parthksingh1** [comment]
@sambhavgupta0705 I want to work on this issue.

**Comment by sambhavgupta0705** [comment]
@parthksingh1 yes you may work on it.

**Comment by sambhavgupta0705** [comment]
@parthksingh1 any updates??
This issue shouldn't take this much of time
