### ISSUE TITLE
[Feature Request]: Add a login button in the navbar

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#29]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

.

**Comment by shramanpaul** [comment]
@sambhavgupta0705  I want to work on this issue. I will add a button which will match the theme of the site and will also link to referred page.

**Comment by Anurag607** [comment]
@shramanpaul any updates?

**Comment by shramanpaul** [comment]
The login button has been made and the redirection of the button is under process. @Anurag607

**Comment by shramanpaul** [comment]
I will be making the PR today @Anurag607
