### ISSUE TITLE
Implement the Hero Section for the Landing Page

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#3]
The design for the hero section is given in the Figma design which can be accessed via the notion link provided in the readme.
The design is subject to change, if you have any better idea feel free to share in the comment section or directly implement.

**Comment by parthksingh1** [comment]
Sir I would like to work on this Issue, Please Assign me this issue.

**Comment by Anurag607** [comment]
Of course.

**Comment by Anurag607** [comment]
@parthksingh1 Any progress so far?

**Comment by parthksingh1** [comment]
Yes Sir working on it , will be done by Today Itself

**Comment by parthksingh1** [comment]
Sir prettier ka kuch config error aa rha h syd config linux ke according set h isliye 
Error: delete `cR`( eslint) esa kuch error h

**Comment by Anurag607** [comment]
try using the methods mentioned in this: https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-eslint-delete-cr-prettier-prettier

**Comment by Anurag607** [comment]
@parthksingh1 any updates?

**Comment by sambhavgupta0705** [comment]
@parthksingh1 what's the update???
Kindly let us know so that we can keep a track.

**Comment by dakshata03** [comment]
@Anurag607 
I would like to work on this issue

**Comment by dakshata03** [comment]
@sambhavgupta0705 @Anurag607 
I would like to work on this Issue.. plz assign it to me.

**Comment by RISHIKESHk07** [comment]
Is this is a better template ?, I would like to contribute to this issue
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/f9269bde-bd14-468b-bbdb-4076efe35c68)

**Comment by sambhavgupta0705** [comment]
yes but just follow the color scheme of website

**Comment by RISHIKESHk07** [comment]
@sambhavgupta0705 i was able make look like this ,


![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/f36c6adc-05fc-4cdd-a318-3f45a8ac17a2)
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/1f0dca09-de34-46db-8c60-3cff7d564fe3)

**Comment by sambhavgupta0705** [comment]
Please share a video instead of photos

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07

**Comment by RISHIKESHk07** [comment]
@sambhavgupta0705 

https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/c10b916f-b9d7-4e62-9e3f-a75dc739c8af

**Comment by sambhavgupta0705** [comment]
@RISHIKESHk07 Please open a pull request

**Comment by Anurag607** [comment]
@RISHIKESHk07 please give us a update on the progress so far

**Comment by RISHIKESHk07** [comment]
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/3f1b5638-9a45-49cd-9d2c-42509748f7cb)
@Anurag607 doing styling part as of now , found the previous version occupies too much space(the one in the pr) so shift to this format
