### ISSUE TITLE
[Feature Request]: Add redirection for login page

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#31]
### Is your feature request related to a problem? Please describe.

On clicking login button the login page must be called .
The page has been made you just need to write function that on clicking the button the user must be redirected to `/login` url .

### Describe the solution you'd like

.

### Developer Help

Ask for help whenever needed.

**Comment by shramanpaul** [comment]
@sambhavgupta0705 I want to work on this issue. I will make the addressed fixes.
