### ISSUE TITLE
[Feature Request]: make the navbar sticky

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#32]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

.

**Comment by parthksingh1** [comment]
sambhavgupta0705 I want to work on this issue.

**Comment by sambhavgupta0705** [comment]
@parthksingh1 You can work on it !!
Go ahead 🚀

**Comment by shramanpaul** [comment]
@sambhavgupta0705  I want to work on this issue . I will make the navbar sticky.
