### ISSUE TITLE
Create a Footer for the site

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#4]
The footer needs to have:

1) A link to the institute website
2) Our Contact details
3) An input form for subscription purpose
The above mentioned components are a must....
Any other addition can be shared in the comment section.

**Comment by achhayapathak** [comment]
what do you want in the footer

**Comment by RISHIKESHk07** [comment]
sir, could you please assign me this issue

**Comment by Anurag607** [comment]
yes, I will assign it to you.

**Comment by RISHIKESHk07** [comment]
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/8153d64f-d2a2-4644-8e0b-bb78371c339e)
this is how the footer looks

**Comment by Anurag607** [comment]
Could we have the subscription component as a column aligned to the right? Also is it responsive?

**Comment by RISHIKESHk07** [comment]
i was able to make it responsive and aligned it properly, any other changes are required?
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/17763ea7-0d93-4cb1-b06b-957fbeae1738)

**Comment by Anurag607** [comment]
take reference from this: https://blog.hubspot.com/hs-fs/hubfs/Screen%20Shot%202022-06-30%20at%202.58.09%20PM.png?width=650&name=Screen%20Shot%202022-06-30%20at%202.58.09%20PM.png
remove that "ADDRESS:" text and have the address below the bottom divider (where website terms and so on are placed)

**Comment by Anurag607** [comment]
@RISHIKESHk07  any updates?

**Comment by RISHIKESHk07** [comment]
@Anurag607 ,i am working on the color scheme and have made footer responsive.

**Comment by RISHIKESHk07** [comment]
Sir, i did some changes, should change anything more?
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/117551967/f1e05cc9-cd99-4b9e-a8d6-195ade321e61)

**Comment by sambhavgupta0705** [comment]
@Anurag607 PTAL

**Comment by Anurag607** [comment]
@achhayapathak I think the icons are way too removed from the rest of the footer...
perhaps we can keep it like in this image?

<img width="780" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/7c2d6379-581b-4042-b225-51f6433aaaa5">

@sambhavgupta0705 what are your thoughts?
