### ISSUE TITLE
[BUG]: In login page , background color does not change in dark mode

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/resource-sharing#46]
### Describe the bug

In login page and signup page, when switched to the dark mode, the background color of the input details box is not changing to dark color. So, the login credentials user entered in the input box and  "Login","SignUp", "IIITDMJ" text is is not visible.

### Expected Behavior

When the user switches to the dark mode, the background-color of the input is expected to change to dark color. So that the login credentials, "Login","SignUp", "IIITDMJ" text  will be visible to the user.

### Screenshots/Videos

<img width="907" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/119884665/35deac51-4624-478e-932a-30250218c73d">

<img width="939" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/119884665/7fa5b849-d190-409e-93a2-aa27f41d6710">

### What device are you using?

Desktop, Mobile

### Operating System

Windows, Android

### What browsers are you seeing the problem on?

Chrome

**Comment by sambhavgupta0705** [comment]
@AkashPaloju yes that's a valid issue you can work on this👍

**Comment by AkashPaloju** [comment]
@sambhavgupta0705  please assign a difficulty tag to this issue
