### ISSUE TITLE
[BUG]: Compress and convert images to webp format

### ISSUE THREAD

**Issue by JawHawk** [bsoc-bitbyte/resource-sharing#48]
### Describe the bug

Most of the images are in png format, specially yellow blob image is of size ~2.2 mb which takes time to load. So compress it and convert all images to webp format. @prajjwalkapoor Is this okay ? 

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/86140365/f292d2f9-1550-4c50-9f06-791e56cd17b4)

**Comment by AkashPaloju** [comment]
@JawHawk I wish to work on it. Please assign it to me. I have all ready converted all png/jpeg images to webp format. I will use  find and replace option in vscode to change the image.png/jpg  to .webp.

**Comment by sambhavgupta0705** [comment]
@JawHawk Thanks for raising this issue 😄 
@AkashPaloju you can work on this issue.
