### ISSUE TITLE
[Feature Request]: Add a preloader 

### ISSUE THREAD

**Issue by Shreyans2004** [bsoc-bitbyte/resource-sharing#49]
### Is your feature request related to a problem? Please describe.

The website is related to study material which may have much content in the future.Generally the website with much stuff takes time for loading and In such cases a preloader attracts the user's attention.
Unishare has no preloader now.

### Describe the solution you'd like

I can add a preloader to the website.It will enhance the website and user's experience too .

**Comment by AyushGovil** [comment]
I have made the necessary changes. Please check the PR => https://github.com/bsoc-bitbyte/resource-sharing/pull/56.
