### ISSUE TITLE
Implement the Category Cards for the Landing Page

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#5]
The design for the the cards is given in the Figma design which can be accessed via the notion link provided in the readme.
The images for the cards used in the design is provided in the public folder.

**Comment by NightFury742** [comment]
@Anurag607, @sambhavgupta0705, I want to contribute to this issue, can you please assign it to me.

**Comment by Anurag607** [comment]
@NightFury742 any progress so far?

**Comment by NightFury742** [comment]
Currently working on this issue,I  will probably close this today itself
