### ISSUE TITLE
[Feature Request]: A new page for displaying the details corresponding

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#51]
This issue will ensure that the users have a brief (but necessary) knowledge regarding the material, allowing them to be more selective in their search.

- Create a page **(the reference image is attached bellow)** while maintaining the color scheme of the site.
- Make sure the page is responsive.
- Add a button for re-directing users to the pdf users (like: Read Now).
- Also maintain the code structure, you can visit the other components to see how they were implemented

You can refer to the below image for inspiration...**make sure to keep the design structure similar**. But there are minor changes here and there.

- **Like you can replace the buy with button with the button required for redirection**.
- you can remove size, publication and size
- binding can be replaced with type denoting the type of material (handwrittern notes, pdf lecture notes, pdf books and so on)

### On Desktop: 
<img width="960" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/bf513a5c-0f7c-429e-84db-c54a4a783ff8">

### On Mobile: 
<img width="363" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/094198cc-adb6-45b9-bdeb-972ae07515c0">
<img width="362" alt="image" src="https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/f8be8860-e2cf-4513-a7f1-d12dbfcb7ac9">

**Comment by shramanpaul** [comment]
I want to work on this issue @Anurag607

**Comment by shramanpaul** [comment]
I will be working with maintaining the color scheme and all the points raised.

**Comment by Anurag607** [comment]
@shramanpaul upload a video covering all aspects of the page once done.

**Comment by shramanpaul** [comment]
Ok @Anurag607

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/110323017/3f796de1-ea3d-46fd-a081-c783c5d8e1e9

@Anurag607  Please review the above

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/110323017/87b3747e-20c5-4f50-b747-8d8ba85a87ab

@Anurag607  Please review the above
