### ISSUE TITLE
[Feature Request]: Implement a PDF Viewer

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#52]
Having an in-built pdf reader will allow user to quickly go through material he/she may be interested, i think having this will be helpful for providing a preview of the material.

- Create a page containing a PDF viewer using react-pdf or PDF.JS while maintaining the color scheme of the site and the code writing structure.
          1. [React-PDF](https://www.npmjs.com/package/react-pdf)
          2. [PDF.JS](https://mozilla.github.io/pdf.js/)
- Make sure this page is responsive.

**Kindly go through the code base to get a feel for how the other components of the site were implemented and adhere to those standards. Also a clean code will be appreciated.**

### Reference Image: 
![WhatsApp Image 2023-06-02 at 14 30 34](https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/f325a37a-8ccc-470b-a1d0-c97b0f88a172)

**Comment by jainvedant392** [comment]
Hello @Anurag607 , I am interested in contributing to this issue. Could you please assign it to me ?

**Comment by jainvedant392** [comment]
I will set the route to the pdf viewer via the "Read now" button mentioned by you in the previous issue

**Comment by Anurag607** [comment]
@jainvedant392 kindly keep us posted regarding related developments here

**Comment by jainvedant392** [comment]
Sure
