### ISSUE TITLE
[Feature Request]: improve the layout of hero section for smaller screen

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#55]
### Is your feature request related to a problem? Please describe.

....

### Describe the solution you'd like

.....

### Developer Help

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/81870866/1afa379b-b007-43e0-ac1b-aaad0e1100c7)

**Comment by avinashji1302** [comment]
Please assign me this!

**Comment by abansal15** [comment]
@sambhavgupta0705 i would like to work on this issue please assign this issue to me

**Comment by sambhavgupta0705** [comment]
@abansal15 we will be assigning on one issue to you so decide whether you want to work on this one or the firebase issue #59

**Comment by abansal15** [comment]
@sambhavgupta0705 assign me this issue as issue #59 is assigned to @RISHIKESHk07

**Comment by abansal15** [comment]
@sambhavgupta0705 can you guide me changes i should follow...

**Comment by abansal15** [comment]
@sambhavgupta0705 i am thinking of firstly reducing the gap between the nav bar and the image it is too large..

**Comment by abansal15** [comment]
how is this ?
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/554d6a1b-caed-4c31-8caa-b42f728d53f0)

**Comment by abansal15** [comment]
for mobile view ?

**Comment by sambhavgupta0705** [comment]
can you please share a video preview

**Comment by abansal15** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/cd414b24-6d92-4165-b923-3b2b5d336d73

**Comment by abansal15** [comment]
@sambhavgupta0705 is it okk ?

**Comment by sambhavgupta0705** [comment]
I kinda liked it,we can go with it .Just open a PR for this and then I can suggest you some more changes

**Comment by abansal15** [comment]
@sambhavgupta0705 Raised the pr
