### ISSUE TITLE
[Feature Request]: Integrate authentication functionality to the existing login/signup page

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#57]
As of now, we have pages ready for login and signup, but they are not functional and so we have to add secure authentication methods for these pages.

Use Firebase native authentication and FireStore database to implement the login and signup feature.

- [ ] Implement Login Functionality
- [ ] Implement Signup functionality

**The below points must be followed:** 
**1. The process must be secure, proper regex for the password section must be added in the signup form (not needed in login page).**
**2. Suitable checks for individual fields must be added as well along with necessary warnings.**
**3. A loader should be added to the both login and signup forms to indicate that login and signup processes are in progress.**
**4. Only use native authentication for this, no other providers (like google, GitHub) are to be used.**
**5. Added an additional check to the email field in both forms, to check if the entered email id belongs to our institute or not.**
**6. The file structure and code structure must be maintained, kindly take a look at the other components for reference.**
**7. All the required functions must be added in Firebase/script.mjs .**
**8. Store the data in the cookies not in the localStorage (use js-cookies NPM library), if necessary.**

**Comment by Anurag607** [comment]
@Akashsah2003 can you send me your discord id?

**Comment by Akashsah2003** [comment]
@Anurag607 Sure, this is my discord id
akashkumarsah
