### ISSUE TITLE
[Feature Request]: Implement functions to upload, store and download PDFs and images using firebase storage.

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#59]
We need to make functions allowing us to upload and store relevant materials in the database and then fetch those materials from the DB along with the associated details.

Use firebase storage to upload and store the material in image/pdf format. Also store the details associated with these materials in the firestore db and fetch them both simultaneously.

- [ ] Implement the required function
- [ ] Integrate these functions with the UI
- [ ] Implement caching for these materials using redux

**Kindly inform us once the functions are ready before integrating them into the UI**

**Comment by abansal15** [comment]
hello @Anurag607 i would like to work on this issue please assign this issue to me

**Comment by Anurag607** [comment]
@abansal15 can you send me your discordID?

**Comment by RISHIKESHk07** [comment]
@Anurag607 , i interested in contributing to  the issue ,i will Implement functions for uploading and storing materials in Firebase Storage and Firestore, fetching them with associated details, and integrate with the UI while caching using Redux.

**Comment by Anurag607** [comment]
@RISHIKESHk07 can you send me you discord id?

**Comment by RISHIKESHk07** [comment]
@Anurag607 discord id  :   the_last_ascended

**Comment by abansal15** [comment]
> @abansal15 can you send me your discordID?

abansal15 is also my discord id

**Comment by sambhavgupta0705** [comment]
@abansal15 what's the update?

**Comment by Anurag607** [comment]
@sambhavgupta0705 , @RISHIKESHk07 is working on this issue

**Comment by sambhavgupta0705** [comment]
oh ok
