### ISSUE TITLE
[Feature Request]: improve the footer

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#60]
### Is your feature request related to a problem? Please describe.

Dicuss the things with us in comments

### Describe the solution you'd like

.

### Developer Help

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/81870866/c43ae998-63ee-436a-8e69-d4fa3924d214)

**Comment by Kushdapush** [comment]
@sambhavgupta0705  I would like to work on this issue please assign it to me

**Comment by sambhavgupta0705** [comment]
@Kushdapush yep you can work with it ,just add some info in the footer plus remove all social icons and add github link of the website plus you can also add linkedIn link of the club there
Also remove the newsletter section and add some colors if you wish to

**Comment by Kushdapush** [comment]
ok I will do it
