### ISSUE TITLE
[Feature Request]: Create a design for the dashboard page and Implement it

### ISSUE THREAD

**Issue by Tusharjain123** [bsoc-bitbyte/resource-sharing#63]
### Is your feature request related to a problem? Please describe.

Dashboard page is not present

### Describe the solution you'd like

Design the dashboard page considering the current website design and color scheme

### Developer Help

- [ ] Designing the dashboard page

- [ ] Implementing the dashboard design

**Comment by Kushdapush** [comment]
@Tusharjain123  I would like to work on this issue

**Comment by Tusharjain123** [comment]
ok @Kushdapush I will assign it to you

**Comment by Anurag607** [comment]
@Kushdapush kindly ensure that the page is responsive and matches with the overall color scheme of the site.
You can refer to dribble  or refero to get some ideas.

**Comment by Kushdapush** [comment]
Ok, will keep that in mind

**Comment by Kushdapush** [comment]
@Anurag607  will you please share your discord ID / any other means of communication to discuss about this issue

**Comment by sambhavgupta0705** [comment]
> @Anurag607 will you please share your discord ID / any other means of communication to discuss about this issue

you can see that in maintainers tag

**Comment by Tusharjain123** [comment]
@Kushdapush any updates?

**Comment by Kushdapush** [comment]
@Tusharjain123 sir I am currently working on implementing the final design of dashboard that was discussed. I will try to make a PR as soon as the work gets over!

**Comment by Kushdapush** [comment]
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/129064700/c75966d9-434a-4a31-bc17-338de1005d24)

Sir this is my progress uptill now, I am currently giving it a finishing touch and working on the responsiveness

**Comment by Tusharjain123** [comment]
@Kushdapush In place of the saved text you can use Bookmark Material and remove the Requests tile.
What you say  @Anurag607
