### ISSUE TITLE
[BUG]:  Dark mode icon does not behave as expected.

### ISSUE THREAD

**Issue by Akashsah2003** [bsoc-bitbyte/resource-sharing#66]
### Describe the bug

https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/dd333b28-bae7-445a-b932-1a42841a6b86

When we navigate to different page in dark mode the page remains in dark mode but the icon changes.

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by Akashsah2003** [comment]
@Anurag607 @sambhavgupta0705 Assign me this issue.

**Comment by Kushdapush** [comment]
hey @Akashsah2003 I guess @AkashPaloju  is already working on this issue

**Comment by Akashsah2003** [comment]
> hey @Akashsah2003 I guess @AkashPaloju is already working on this issue

Oh sorry I didn't see the issue I will close the issue as well as the pr.
