### ISSUE TITLE
create a favicon and replace it with the default vite favicon

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#7]
Currently we are using vite's default favicon,we need to replace it with a new one

**Comment by younome71** [comment]
Sir, please assign me this issue

**Comment by Anurag607** [comment]
@younome71 Any progress so far?

**Comment by sambhavgupta0705** [comment]
hey @younome71 any progress so far?

**Comment by younome71** [comment]
It will be done by this evening

**Comment by younome71** [comment]
It will be done by this evening
