### ISSUE TITLE
[Feature Request]: There should be a logo of site

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/resource-sharing#72]
### Is your feature request related to a problem? Please describe.

There is no logo on the website page..
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/da538098-fe29-41e1-b7f9-eae4d99e819a)

### Describe the solution you'd like

If a logo is also added aside the Unishare word it will be more attractive..

**Comment by abansal15** [comment]
hello @sambhavgupta0705 please asisgn this issue to me

**Comment by sambhavgupta0705** [comment]
@abansal15 find some more fixes in the landing page and report them here

**Comment by sambhavgupta0705** [comment]
@younome71 add the logo with a name `unishare` in the footer also beside github and linkedIn card and make them align

**Comment by younome71** [comment]
Ok @sambhavgupta0705

**Comment by Anurag607** [comment]
@younome71 any updates?

**Comment by sambhavgupta0705** [comment]
don't worry about these errors they will be there
