### ISSUE TITLE
[Feature Request]: Add scroll-to-top button for the whole website

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#76]
### Is your feature request related to a problem? Please describe.

Add a scroll to top button for all the pages for the website.
You can add a new component for this.

### Describe the solution you'd like

..

**Comment by Pratik2026** [comment]
I would like to work on this issue

**Comment by parthksingh1** [comment]
Sir please assign this to me

**Comment by prateekjha1204** [comment]
I would like to work on this issue @sambhavgupta0705

**Comment by sambhavgupta0705** [comment]
@Pratik2026 I don't mind if you work on this issue but I want some new contributor to work on this issue as it is very simple issue,you just need to add a component in it.
I opened this for some new contributors so that they can also learn how to contribute to open source

**Comment by prateekjha1204** [comment]
@sambhavgupta0705 I would also like to work on this issue

**Comment by Pratik2026** [comment]
@sambhavgupta0705 It's totally fine, you can assign this to someone else.

**Comment by sambhavgupta0705** [comment]
@Pratik2026 I appreciate your this gesture,I will be opening some new issues soon related to backend you can check them as well

**Comment by Kushdapush** [comment]
@sambhavgupta0705  please assign me this issue

**Comment by prateekjha1204** [comment]
@sambhavgupta0705 I would also like to work on this issue

**Comment by Pratik2026** [comment]
@sambhavgupta0705 Sure I am looking forward to it.

**Comment by sambhavgupta0705** [comment]
@prateekjha1204 I have assigned you one issue,so I am giving @Kushdapush a chance to work on this

**Comment by sambhavgupta0705** [comment]
@Kushdapush any updates

**Comment by Kushdapush** [comment]
work is in progress, I will make a pr today itself

**Comment by Kushdapush** [comment]
https://github.com/bsoc-bitbyte/resource-sharing/assets/129064700/e2b18671-e1e5-4e89-b366-67f38cfa3dd6

@sambhavgupta0705  here's the preview
