### ISSUE TITLE
[Feature Request]: enable remember me button on login page

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#77]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/81870866/0727c5f6-42bb-4511-a9dc-fb27f12847aa)
Here you can see there is a remember me button which will auto login the user whenever he opens the site.
I think its to enable it. You can take inspiration from how [https://bitbytesummerofcode.netlify.app/](https://bitbytesummerofcode.netlify.app/) works.

### Describe the solution you'd like

..

**Comment by parthksingh1** [comment]
I would like to work on this issue @sambhavgupta0705

**Comment by ojasvatomar47** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Akashsah2003** [comment]
@sambhavgupta0705 I already enabled it in my last pr. I think it's working fine.

**Comment by sambhavgupta0705** [comment]
Ohh yeah thanks @Akashsah2003 I totally forgot about it
