### ISSUE TITLE
[BUG]: remove email subscription from footer

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#78]
### Describe the bug

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/81870866/13296097-d0eb-4a75-890b-6139c6bc2926)

**Comment by ojasvatomar47** [comment]
I would like to work on this issue. Please assign it to me

**Comment by younome71** [comment]
I would like to work on this issue, please assign it to me
