### ISSUE TITLE
[Feature Request]: Make footer compatible with dark mode

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#79]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

.

**Comment by sambhavgupta0705** [comment]
@abansal15 will you be working on this one also #72 ??

**Comment by abansal15** [comment]
@sambhavgupta0705 yes I will do

**Comment by sambhavgupta0705** [comment]
@abansal15 well these are very simple issues which I am opening which are for new commers who haven't contributed much and want to. I appreciate your willingness to work on this issue but I suggest work on one issue for now and give chance to others also

**Comment by sambhavgupta0705** [comment]
then I suggest let @younome71 work on that???

> @sambhavgupta0705 issue #72 is very small not take much time please assign me

**Comment by abansal15** [comment]
ok @sambhavgupta0705  let @younome71 work on the issue #72 but please give this to me

**Comment by sambhavgupta0705** [comment]
@younome71 you may work on #72 I am adding more task in it for you

**Comment by younome71** [comment]
Ok @sambhavgupta0705

**Comment by abansal15** [comment]
@sambhavgupta0705 in my issue #55 I don't know when you deploy the site again it has some problem I have seen it now 
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/c4a3fe83-98f7-4245-856b-15ab67dab422)
but now I have fixed it also
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/0aed406c-a5ac-4095-bff6-5c81440f524c)
in my pr of this issue, it will be resolved
I'm sorry for inconvenience..

**Comment by abansal15** [comment]
@sambhavgupta0705 i have fixed all the changes that should occur in dark mode but onlt the problem i am facing is how to set this background color to dark.
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/120590200/55f3d16a-4d49-45a9-b9f4-dc4b6772ded3)
in the style one ??

**Comment by Anurag607** [comment]
@abansal15 remove the style tag and convert it to tailwindcss

**Comment by abansal15** [comment]
@sambhavgupta0705 is it ok  ?

**Comment by abansal15** [comment]
@sambhavgupta0705 please review the pr
