### ISSUE TITLE
create a contributing.md file

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#8]
You have seen a contributing.md file for large codebase in which they explain how to contribute, creating branch and opening a PR.
We need the same for this project ,you can take inspiration from 
- https://github.com/asyncapi/website/blob/master/CONTRIBUTING.md
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Sections you need to add 
- Contribution workflow
- How to create an issue
- how to create a pull request

**Comment by parthksingh1** [comment]
Sir, I would like to work on this issue. Please assign it to me.

**Comment by RISHIKESHk07** [comment]
sir can i work on this issue

**Comment by Charan2437** [comment]
Sir ,can I work on this issue..
