### ISSUE TITLE
[BUG]: Project unable to start 

### ISSUE THREAD

**Issue by AyushGovil** [bsoc-bitbyte/resource-sharing#82]
### Describe the bug

The project doesn't show anything on the browser. 

### Steps To Reproduce

Follow the steps mentioned in the [readme.md](https://github.com/bsoc-bitbyte/resource-sharing#run-locally) file to setup the project in local. On starting the project the browser doesn't show anything.

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/33975149/cb8cd171-62c1-44ff-8cd0-0c8f69c6baf9)

![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/33975149/3e67c663-ba4a-480f-9e13-cc372fa92202)

### What device are you using?

Desktop

### Operating System

Windows

**Comment by sambhavgupta0705** [comment]
@AyushGovil yes we know about that error, you need to add firebase keys in the .env file.

**Comment by AyushGovil** [comment]
Ok @sambhavgupta0705 . We need to create an .env file as that is not in the project I see.

**Comment by sambhavgupta0705** [comment]
@AyushGovil I have created an issue for ir ,well for now I have given it to someone else .I will assign you an issue soon. I know that you deserved that issue but I totally forgot it so will assign a new issue to you soon 😄
