### ISSUE TITLE
[Feature Request]: Add .env file 

### ISSUE THREAD

**Issue by sambhavgupta0705** [bsoc-bitbyte/resource-sharing#83]
### Is your feature request related to a problem? Please describe.

As we have firebase as a backend now so the application will not start without the keys.
So make a `.env` file and add keys in it.
You also need to make some changes in readme also in the project setup guidelines

### Describe the solution you'd like

The file structure should be like this ⬇️ 

```VITE_FIREBASE_API_KEY=
VITE_FIREBASE_AUTH_DOMAIN=
VITE_FIREBASE_PROJECT_ID=
VITE_FIREBASE_STORAGE_BUCKET=
VITE_FIREBASE_MESSAGING_SENDER_ID=
VITE_FIREBASE_APP_ID=
VITE_FIREBASE_MEASUREMENT_ID=

**Comment by shramanpaul** [comment]
i want to work on this issue @sambhavgupta0705

**Comment by shramanpaul** [comment]
I will be making the requested changes and addition of files.

**Comment by prateekjha1204** [comment]
I want to work on this issue @sambhavgupta0705

**Comment by sambhavgupta0705** [comment]
@shramanpaul as you commented first so you can work on this issue

**Comment by sambhavgupta0705** [comment]
@shramanpaul any updates.

**Comment by shramanpaul** [comment]
Yes I have made the .env file and will be making further changes @sambhavgupta0705

**Comment by shramanpaul** [comment]
@sambhavgupta0705  what name should I give to the .env file?

**Comment by sambhavgupta0705** [comment]
`.env_example`

**Comment by sambhavgupta0705** [comment]
@shramanpaul

**Comment by shramanpaul** [comment]
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/110323017/28518787-5c66-47a5-93e4-50a80d495c60)
@sambhavgupta0705  PTAL 
 do I need to make changes ?

**Comment by Anurag607** [comment]
@shramanpaul Just add "" in front of them all
