### ISSUE TITLE
[BUG]: Dark mode icon not behaving properly.

### ISSUE THREAD

**Issue by Akashsah2003** [bsoc-bitbyte/resource-sharing#92]
### Describe the bug

When we navigate to a different page dark mode icon is not working as expected. Also if the user prefers dark mode then the website should be rendered as dark mode in initial state.

https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/54b0d7ba-3d6b-490a-a0f8-a48cd9bb7520

https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/094a322f-9b8e-47df-93fe-c14e9d4a60e9

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

### Additional context

This bug was solved previously but was reintroduced in one of the commits.

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 I don't know why you created this issue.Like what's the need of this issue. I think its working fine for now.For the time our main is to make our website functional. Like you are now familiar with this project and how many times dark mode will be fixed.It has been fixed earlier.
Try to look for some big issues or create a compilation of minor issues so that we can improve the UI of the website.
Don't try to pile up the github issues section. Create issues which can add some good value to the project and you can upskill yourself from it.

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 in your pr you have also pushed packagelock.json which I think was not recommended if you are not adding any new npm package to the project

**Comment by Akashsah2003** [comment]
@sambhavgupta0705 In the vercel deployment of the website the button was not working properly. So I created this issue. Also, I pushed packagelock.json because one of the previous merge conflicts was not properly solved and the code is not written neatly as you can see in the image here and I just removed these.
![image](https://github.com/bsoc-bitbyte/resource-sharing/assets/73382164/a8c14a31-02ce-46eb-8b24-4de96464c903)

Although I understand that it may be not a good practice to upload the packagelock.json. I will close this issue as it is not required. 

I want to work on integrating uploading, downloading, viewing and caching the materials with the UI. I would request you to create this issue and assign it to me and also guide me with the changes required. Also I am thinking that we can setup vercel auto deployment as it is not deploying properly as of now which will make the process of pr reviewing easier for the mantainers as well as contributors. So please create this issue if you deem the need for it.

Thank you for guiding me.

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 vercel asks for cash to show previews on every commit.
We thought of this a very long time ago and tried installing it. Currently the preview which you have at unishare.vercel.app it is only being deployed manually on our private  repository.

Give us also some time we are very much occupied by other works and we need to prepare for our upcoming semester also so we can't devote that much of time.
Hopefully from Monday I will try to make new issues.

Thank you and try creating only valid issues.
