### ISSUE TITLE
[Feature Request]: Add a form to facilitate the material upload process

### ISSUE THREAD

**Issue by Anurag607** [bsoc-bitbyte/resource-sharing#94]
We need a form in the dashboard to allow users to upload the materials/resources.

This will be a modal form linked to the dashboard which open on click.

- Add a button in the dashboard to open the form.
- The form needs to be a separate component which will open when clicked on the button mentioned above, utilize redux to achieve.
- the form needs to be have the following fields: 

1. Text field for title
2. Text area field for description
3. File upload field for images, make it so that you can upload multiple files at ones
4.  File upload field for pdf, limit to only one pdf only.
5. A submit button

***This modal form component needs to be responsive as well.**

Refer to the below image for a general idea, 
![WhatsApp Image 2023-07-17 at 18 13 22](https://github.com/bsoc-bitbyte/resource-sharing/assets/64116092/749dfedf-885b-4e64-b8f4-2de9a80f0a18)

**Comment by Akashsah2003** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Anurag607** [comment]
@Akashsah2003 go ahead

**Comment by RISHIKESHk07** [comment]
I would like to contribute to this issue

**Comment by sambhavgupta0705** [comment]
@Akashsah2003 You can work on this issue just one things can we need to complete this by tomorrow

**Comment by Akashsah2003** [comment]
@sambhavgupta0705 I can do that.

**Comment by Anurag607** [comment]
@Akashsah2003 please read the issue, I have explicitly mentioned that the form needs to be a modal, a popup modal is preferred.
